[tools]
copier = "9"
git-cliff = "2"
"pipx:bump-my-version" = "1"
shellcheck = "0.11"

[tasks.pre-commit]
description = "Run pre-commit"
run = "pre-commit run --all-files --color always"

[tasks."bump-version"]
description = "Bump the project version"
run = "bump-my-version bump --new-version $( git-cliff --bump --bumped-version --output - )"

[tasks.git-push]
description = "Push the current branch and related tags"
run = "git push --follow-tags origin HEAD"

[tasks.update-changelog]
description = "Update the project changelog"
run = """
  #!/usr/bin/env bash
  set -eo pipefail

  git-cliff --output CHANGELOG.md

  if [[ "$1" == "--commit" ]] ; then
    git add -- CHANGELOG.md
    [[ -n "$( git diff --staged -- CHANGELOG.md )" ]] && git commit -m "docs: update changelog" || true
  fi
"""

[tasks.clean]
description = "Cleanup generated files"
run = """
  #!/usr/bin/env bash
  set -x
  case "$1" in
    /tmp|.|"$PWD")
      echo "WARN: refusing to remove directory '$1'"
      exit 0
    ;;
  esac
  rm -rf -- "$1"
"""

[tasks.generate]
description = "Generate project using the local template directory"
usage = '''
  arg "<output_dir>" help="Output directory" default="output/example-repo"
'''
run = [
  'mise run clean -- "${usage_output_dir}"',
  'copier copy --trust --vcs-ref HEAD . "${usage_output_dir}"',
]
